### 1. Получить все задачи
GET http://localhost:8080/tasks

###

### 2. Создать новую задачу
POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "Выпить",
  "deadline_time": "2026-07-20 18:10:01"
}

### 3. Сменить статус задачи
PATCH http://localhost:8080/tasks/change
Content-Type: application/json

{
  "id": 7
}

### 4. Удалить(архивировать) задачу
DELETE http://localhost:8080/tasks/delete
Content-Type: application/json

{
  "id": 2
}